apiVersion: v2
name: cert-exporter
description: A Helm chart for SSL Certificate Expiry Prometheus Exporter
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - prometheus
  - exporter
  - certificate
  - ssl
  - monitoring
home: https://github.com/kevin197011/cert-exporter
sources:
  - https://github.com/kevin197011/cert-exporter
maintainers:
  - name: kevin197011
    email: kevin197011@example.com